### ISSUE TITLE
[REQUEST]Use embedded lyrics

### ISSUE THREAD

**Issue by Jkkoi** [Rachel030219/Poweramp-LRC-Plugin#9]
Lyrics used in song tags

**Comment by Rachel030219** [comment]
Currently not in development plan.

**Poweramp itself is already able to read embedded lyrics** , thus it is unnecessary for any third plugin to implement that feature again.

If what you mean is synchronized embedded lyrics, though I'd like to add that feature, it is too early for this project, since there are still many bugs to fix and lots of things to do as it is still at the alpha stage.

Anyway, thanks for your report.

**Comment by Rachel030219** [comment]
This feature has been released in version 1.4.
